version: "3.9"

services:
  notifications_database:
    image: postgres
    container_name: notifications_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=messias
      - POSTGRES_PASSWORD=teste
      - POSTGRES_DB=pushNotifications
    volumes: 
      - pgdata:/data/postgres

  app:
    build: .
    container_name: notifications_container
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - notifications_database
    depends_on:
      - notifications_database


volumes:
  pgdata:
    driver: local
